version: "2"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "Intentionally wrong syntax
      MYSQL_USER: synergy
      MYSQl_PASSWORD: "Remove double quote and generate good password
      MYSQL_DATABASE: synergymain
    volumes:
      - ../docker-runtime/mysql:/var/lib/mysql

  php:
    image: wodby/drupal-php:7.0
    environment:
      DEPLOY_ENV: dev
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
    links:
      - db
    volumes:
      - ./html:/var/www/html
      - ./vendor:/var/www/vendor

  nginx:
    hostname: drupal-synergy
    image: wodby/drupal-nginx:8-1.10
    environment:
      NGINX_BACKEND_HOST: php
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    depends_on:
      - php
    volumes_from:
      - php
    ports:
      - "8701:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8725:8025"

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: synergy
      PMA_PASSWORD: mUUiTKegXN3uD33m
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8780:80"
